- hosts:
  - ec2-k8s-m2
  - ec2-k8s-m3
  become: yes
  tasks:
    - name: "Reset cluster"
      shell: "kubeadm reset -f"

    - name: "Fazendo join kubernetes master"
      shell: kubeadm join k8s-haproxy:6443 --token psygxi.x9ly3migo0xksx4v  --discovery-token-ca-cert-hash sha256:8ff4eef689ae23dc8114803da5d80b6157400d59ef33c37ac0df0ee96e6da720  --control-plane --certificate-key b677efbec66e60c89daa406a0cd7a95d92afa7eaa4228945bfb4e225347ffe40

    - name: "Colocando no path da maquina o conf do kubernetes"
      shell: mkdir -p /home/ubuntu/.kube && sudo cp -f /etc/kubernetes/admin.conf /home/ubuntu/.kube/config && sudo chown 1000:1000 /home/ubuntu/.kube/config && export KUBECONFIG=/etc/kubernetes/admin.conf
#---
- hosts:
  - ec2-k8s-w1
  - ec2-k8s-w2
  - ec2-k8s-w3
  become: yes
  tasks:
    - name: "Reset cluster"
      shell: "kubeadm reset -f"

    - name: "Fazendo join kubernetes worker"
      shell: kubeadm join k8s-haproxy:6443 --token psygxi.x9ly3migo0xksx4v  --discovery-token-ca-cert-hash sha256:8ff4eef689ae23dc8114803da5d80b6157400d59ef33c37ac0df0ee96e6da720 

#---
- hosts:
  - ec2-k8s-m1
  become: yes
  tasks:
    - name: "Configura weavenet para reconhecer os nós master e workers"
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

    - name: Espera 30 segundos
      wait_for: timeout=30

    - shell: kubectl get nodes -o wide
      register: ps
    - debug:
        msg: " '{{ ps.stdout_lines }}' "
