- hosts: ec2-java-app
  handlers:
    - name: "restart nginx"
      service:
        name: nginx
        state: restarted
      become: yes
    - name: "restart mysql"
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:
    - name: "Roda: sudo apt update"
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #Um dia
    
    # - name: "Instala pacotes em lote"
    #   apt:
    #     name: "{{ item }}"
    #     state: latest
    #   become: yes # roda com sudo
    #   with_items:
    #     - nginx
    #     - openjdk-11-jre-headless
    #     - maven
    #     - mysql-server
    #     - unzip

    # - name: "Clone do projeto"
    #   ansible.builtin.git:
    #     repo: "https://github.com/torneseumprogramador/spring-web-youtube"
    #     dest: "/home/ubuntu/spring-web-youtube"
    #     clone: yes
    #     update: yes
    
    - name: Adicionar USER no bashrc
      lineinfile: dest=~/.bashrc line='export USER=root state=present'
      become: yes

    - name: Adicionar PASSWORD no bashrc
      lineinfile: dest=~/.bashrc line='export PASSWORD=root state=present'
      become: yes

    - name: Adicionar DATABASE_URL no bashrc
      lineinfile: dest=~/.bashrc line='export DATABASE_URL="mysql://localhost:3306/treinamento_database" state=present'
      become: yes

    - name: "Valida bashrc"
      shell: "source ~/.bashrc"
      become: yes

    # - name: "Fazendo descompactação dos arquivos do WP"
    #   unarchive:
    #     src: "/tmp/wordpress.tar.gz"
    #     dest: "/var/www"
    #     remote_src: yes
    #   become: yes  

    # - name: "Copia arquivo WP"
    #   copy:
    #     src: '/var/www/wordpress/wp-config-sample.php'
    #     dest: '/var/www/wordpress/wp-config.php'
    #     remote_src: yes
    #   become: yes

    # - name: "Configura o wp-config com as senhas"
    #   replace:
    #     path: '/var/www/wordpress/wp-config.php'
    #     regexp: "{{ item.regex }}"
    #     replace: "{{ item.value }}"
    #   with_items:
    #     - { regex: 'nome_do_banco_de_dados_aqui', value: 'banco_wordpress' }
    #     - { regex: 'nome_de_usuario_aqui', value: 'root' }
    #     - { regex: 'senha_aqui', value: 'root' }
    #   become: yes

    # ### Altera direto no apache
    # - name: "altera apache"
    #   replace:
    #     path: '/etc/apache2/sites-available/000-default.conf'
    #     regexp: "{{ item.regex }}"
    #     replace: "{{ item.value }}"
    #   with_items:
    #     - { regex: '/var/www/html', value: '/var/www/wordpress' }
    #   become: yes

    # - name: "Trocando pasta do render do apache para o wordpress"
    #   copy:
    #     src: "apache/000-default.conf"
    #     dest: "/etc/apache2/sites-available/000-default.conf"
    #   become: yes
    #   notify:
    #     - "restart apache"

    - name: "Lavanta serviço do mysql"
      become: yes
      service:
        name: mysql
        state: started

    - name: "Criando senha root mysql"
      become: yes
      mysql_user:
        name: root
        host: localhost
        password: root
        priv: "*.*:ALL,GRANT"

    # - name: "Cria o banco de dados MySQL"
    #   mysql_db:
    #     name: treinamento_database
    #     login_user: root
    #     login_password: root
    #     state: present

    - name: "Build package do Java"
      shell: "cd spring-web-youtube && mvn package"

    - name: "Trocando nginx para VPS"
      copy:
        src: "nginx/default"
        dest: "/etc/nginx/sites-available/default"
      become: yes
      notify:
        - "restart nginx"

"
QUOTATION MARK
Unicode: U+0022, UTF-8: 22
|
VERTICAL LINE
Unicode: U+007C, UTF-8: 7C
'
APOSTROPHE
Unicode: U+0027, UTF-8: 27