apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  # namespace: umnamespace # para colocar em um namespace diferente
spec:
  template:
    metadata:
      name: leandsu-nodejs
      labels:
        app: leandsu-nodejs # tag para associar recursos
    spec:
      containers:
        - name: container-pod-nodejs # a imagem está no dockerhub
          image: leandsu/app-validadorcpf-java
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "512Mi" # 512 MB
              cpu: "0.5" # 1 milicors VCPU # este recurso tira do meu cluster este recurso #https://www.datacenters.com/news/what-is-a-vcpu-and-how-do-you-calculate-vcpu-to-cpu https://www.hyve.com/what-is-a-vmware-vcpu/
            limits: # caso a aplicação precise de mais recurso, ele coloca este limite automático
              memory: "800Mi" # 800 MB
              cpu: "1"

          # env:
          #   - name: "DATABASE_URLS"
          #     value: "https://usuario@senha:mysql.server:3306"
  replicas: 3
  selector:
    matchLabels:
      app: leandsu-nodejs


# $ kubectl apply -f deployment-nodejs.yml
# $ kubectl describe -f deployment-nodejs.yml
# $ kubectl delete -f deployment-nodejs.yml
# $ kubectl logs -l app=lable-pod-nodejs # log de todos os lables do replicaset
# $ kubectl logs --tail=20 --follow=true -l app=lable-pod-nodejs
# $ kubectl rollout history deployment
# $ kubectl annotate deployment.apps/nodejs-deployment kubernetes.io/change-cause="levantando mudando a variavel de ambiente"
# $ kubectl rollout undo deployment.apps/nodejs-deployment --to-revision=2
# $ kubectl scale deployment.v1.apps/nodejs-deployment --replicas=2

# $ kubectl autoscale deployment.v1.apps/nodejs-deployment --min=2 --max=5 --cpu-percent=80


# $ kubectl get pod -o yaml > teste.yml # exportando yaml do pod do kubernets


# $ kubectl apply -f deployment-site.yaml
# $ kubectl delete -f deployment-site.yaml
# $ kubectl get deployment
# $ kubectl describe deployment site-deployment
# $ kubectl rollout history deployment site-deployment
# $ kubectl annotate deployment.v1.apps/site-deployment kubernetes.io/change-cause="teste de comentário"
# $ kubectl rollout undo deployment.v1.apps/site-deployment --to-revision=2
# $ kubectl get rs
# $ kubectl get rs -w
# $ kubectl get pods -o wide
# $ kubectl scale deployment.v1.apps/site-deployment --replicas=2
# $ kubectl autoscale deployment.v1.apps/site-deployment --min=5 --max=8 --cpu-percent=80
# $ kubectl get hpa # mostra status autoscale
# $ kubectl delete hpa site-deployment
# $ kubectl delete horizontalpodautoscaler --all
# $ kubectl set image deployment.v1.apps/site-deployment nginx=nginx:latest
# $ kubectl run didox-nginx-memoria --image=nginx --requests=cpu=500m,memory=500M --expose --port=80
# $ kubectl autoscale deployment didox-nginx-memoria --cpu-percent=50 --min=1 --max=10
# $ kubectl create namespace bancodedados # cria namespaces para organizar seus pods e recursos
# $ kubectl get pods -n bancodedados # lista recursos do namespace
