- hosts: all
  become: true

  tasks:

    - name: "Restart docker"
      shell: sudo systemctl daemon-reload && sudo systemctl restart docker && sudo systemctl restart kubelet

    - name: "Valida docker"
      shell: systemctl status docker | grep running | wc -l
      register: docker
      failed_when: docker.stdout == "0"

    - name: "Valida k8s"
      shell: kubectl -- version | wc -l
      register: kubelet
      failed_when: kubelet.stdout != "0"

    - name: "Valida Ansible"
      shell: ansible --version | grep ansible.cfg | wc -l
      register: ansible
      failed_when: ansible.stdout != "1"