- hosts: kubernets-master
  become: yes
  tasks:
    - name: "Copia os arquivos para executar o deployment dos pods"
      copy:
        src: "k8s"
        dest: "/root/"
      
    # - name: "Aplica o deployment de DEV"
    #   shell: kubectl apply -f /root/k8s/deployment_dev.yml

    # - name: "Aplica o deployment de STAGE"
    #   shell: kubectl apply -f /root/k8s/deployment_stage.yml

    - name: "Aplica o deployment de PROD"
      shell: kubectl apply -f /root/k8s/deployment_prod.yml

    - name: "Valida o deployment dos Pods"
      shell: kubectl get all -o wide

    # - name: "Upload k8s-deploy"
    #   copy:
    #     src: "k8s-deploy"
    #     dest: "/root/"
    
    # - name: "Aplicar configmap"
    #   shell: kubectl apply -f /root/k8s-deploy/7-mysql-configmap.yml

    # - name: "Aplicar secret"
    #   shell: kubectl apply -f /root/k8s-deploy/7.1-mysql-secret.yml

    # - name: "Aplicar mysql"
    #   shell: kubectl apply -f /root/k8s-deploy/7.2-mysql.yml

    # - name: "Aplicar secret"
    #   shell: kubectl apply -f /root/k8s-deploy/7.3-deployment.yml

    # - name: "Aplicar nodeport"
    #   shell: kubectl apply -f /root/k8s-deploy/7.4-nodeport-javadb.yml

    # - name: "Aplicar hpa"
    #   shell: kubectl apply -f /root/k8s-deploy/7.5-hpa-javadb.yml

    - shell: "kubectl get pods"
      register: ps
    - debug:
        msg: " '{{ ps.stdout_lines }}' "

# ansible-playbook -i hosts provisionar.yml -u ubuntu --private-key ~/Desktop/devops/treinamentoItau